# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
#stripe_api_key: 7eb93dc2-935d-4bd0-8508-5023d5ae4cdf
#stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
#production:
  #stripe_api_key: 7eb93dc2-935d-4bd0-8508-5023d5ae4cdf
  #stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
